console.log(" ".repeat(7)+"A")
console.log(" ".repeat(6)+"B"+" "+"B")
console.log(" ".repeat(5)+"C"+" ".repeat(3)+"C")
console.log(" ".repeat(4)+"D"+" ".repeat(5)+"D")
console.log(" ".repeat(3)+"E"+" ".repeat(7)+"E")
console.log(" ".repeat(4)+"D"+" ".repeat(5)+"D")
console.log(" ".repeat(5)+"C"+" ".repeat(3)+"C")
console.log(" ".repeat(6)+"B"+" "+"B")
console.log(" ".repeat(7)+"A")