console.log("-".repeat(39))
console.log("|"+" ".repeat(37)+"|")
console.log("|"+" ".repeat(37)+"|")
console.log("|"+" ".repeat(37)+"|")
console.log("|"+" ".repeat(37)+"|")
console.log("|"+" ".repeat(37)+"|")
console.log("-".repeat(39))