nome1 = io.read()
nome2 = io.read()
nome3 = io.read()
nome4 = io.read()
nome5 = io.read()
nome6 = io.read()
nome7 = io.read()
nome8 = io.read()
nome9 = io.read()
nome10 = io.read()

print(nome3)
print(nome7)
print(nome9)