nome1 = input("A: ")
nome2 = input("A: ")
nome3 = input("A: ")
nome4 = input("A: ")
nome5 = input("A: ")
nome6 = input("A: ")
nome7 = input("A: ")
nome8 = input("A: ")
nome9 = input("A: ")
nome10 = input("A: ")

print(nome3)
print(nome7)
print(nome9)